In [1]:
!git clone https://github.com/yilundu/reduce_reuse_recycle.git
%cd reduce_reuse_recycle

Cloning into 'reduce_reuse_recycle'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 93 (delta 21), reused 70 (delta 10), pack-reused 0
Unpacking objects: 100% (93/93), 2.64 MiB | 9.22 MiB/s, done.


Download the checkpoint trained on "Cubes", "Spheres" and "Cylinder" Shapes

In [3]:
!gdown https://drive.google.com/uc?id=19ay4bLVCQho8_aXtODWbDCpu6L2l58YB

Downloading...
From: https://drive.google.com/uc?id=19ay4bLVCQho8_aXtODWbDCpu6L2l58YB
To: /content/reduce_reuse_recycle/ebm-49x1874.pt
100% 501M/501M [00:09<00:00, 53.8MB/s]


In [8]:
!python inf_sample.py --sampler Rev_Diff --ckpt_path "ebm-49x1874.pt"

Using energy mode
A cube
A cylinder
tensor([[[0],
         [2]]])
torch.Size([1, 2, 1])
tensor([[0],
        [2],
        [0]])
[True, True, False]
torch.Size([3, 1])
Using Reverse Diffusion Sampling only
Using Sampler:  Rev_Diff
100% 100/100 [00:19<00:00,  5.08it/s]
100% 100/100 [00:20<00:00,  4.98it/s]
100% 100/100 [00:18<00:00,  5.37it/s]
100% 100/100 [00:18<00:00,  5.35it/s]


In [12]:
!python inf_sample.py --sampler ULA --ckpt_path "ebm-49x1874.pt"

Using energy mode
A sphere
A cylinder
tensor([[[1],
         [2]]])
torch.Size([1, 2, 1])
tensor([[1],
        [2],
        [0]])
[True, True, False]
torch.Size([3, 1])
Using Sampler:  ULA
100% 100/100 [03:20<00:00,  2.00s/it]
100% 100/100 [03:19<00:00,  2.00s/it]
100% 100/100 [03:20<00:00,  2.00s/it]
100% 100/100 [03:19<00:00,  2.00s/it]
